### ISSUE TITLE
Evaluate document generation tool like Sphinx / Doxygen

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#12]
As an IMPROVER developer, I want a document generation tool to be chosen and implemented so that I can write my docstrings accordingly and create automatic code documentation.

Acceptance criteria:
 * Talk to Rose team about https://github.com/metomi/rose/pull/2046
 * Also see Iris 
 * Choose a document generation tool and justify choice with pros/cons
 * Prototype on a part of the IMPROVER codebase, adjusting docstrings as necessary

**Comment by arh89** [comment]
A list of python compatible documentation generator tools can be found on wikipedia:
https://en.wikipedia.org/wiki/Comparison_of_documentation_generators

The ones which are most commonly mentioned online (and therefore probably the most widely used) are: **Epydoc**, **Sphinx**, **Doxygen** and **pydoc**.

Going through each of these in turn:

# Epydoc
* Example documentation: http://epydoc.sourceforge.net/api/

## Pros:
* Most commonly uses its own markup language (Epytext: http://epydoc.sourceforge.net/epytextintro.html), which is quite nice (though we will need to change our style) and very lightweight. It can also use reStructuredText, which is used by other tools (Sphinx).
* Seems to be able to generate nice call/inheritance graphs (though unsure if these are generated by an external tool).
* Open source (MIT license), so able to edit if we need to.

## Cons:
* Generated documentation looks a little outdated out of the box (though it seems to be customizable).
* Inactive? Last stable release in 2008 – might break in the future.
* An additional external dependency on the code.

# Sphinx
* Example documentation: http://www.sphinx-doc.org/en/stable/tutorial.html  https://docs.python.org/

## Pros:
* Seems to be the “standard” for python documentation – used by python, numpy, scipy, iris, rose etc.. This means that common problems will likely have a well documented solution.
* Open source (BSD license) – active development.
* Can link into github/bitbucket etc through (e.g) https://readthedocs.org – automated documentation generation based on a new commit to the repository (can this generate a pass/fail within testing framework?).
* Generated documentation looks good out of the box.
* Through the “napoleon” plugin (+ “autodoc”) can extract documentation based on Google/numpy style docstrings (reStructuredText by default).
* Seems to have integration of doctests – might be able to test these while compiling documentation?

## Cons:
* Another external dependency (though somewhat mitigated by Sphinx being installed internally).
* Not an API generation documentation tool – designed for handwritten documentation (user guides), but has a plugin to automatically extract documentation from source code. Might be a bit tricky to set up.
* Since it’s not an API documentation tool, generating call/inheritance graphs might be difficult (we can include graphviz graphs, but will need to use something else like pycallgraph (called from within Sphinx?) or similar)…

# Doxygen
* Examples: http://www.stack.nl/~dimitri/doxygen/   http://www.vtk.org/doc/nightly/html/index.html

## Pros:
* Designed for API documentation, rather than hand written documentation – large feature set and can easily generate things like call/inheritance graphs. (Might also be a con)
* Open source (GPLv2) and in active development.
* Large language support (C, Fortran, Python etc) – can use the same tool for many projects.
* Reasonable looking documentation (not as nice as Sphinx, but better than Epydoc).

## Cons:
* External dependency but installed internally.
* Not python specific – some of the syntax can be a bit ugly (more overhead for developers).
** Python use looks like: http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html
** Seem to need to use ## syntax to get access to special @commands: eg: @package @param @var etc.. Unclear how much of the documentation can be placed into docstrings rather than comments. Are docstrings just limited to more basic documentation?
* Since well suited to API documentation, might be difficult to use for a user guide or similar.

# Pydoc

# Pros:
* Included as part of python (no external dependencies).
* Very straightforward to use (no overhead).
* Good for simple (as-is) documentation, particularly well suited to small projects.

# Cons:
* Limited knowledge of structure of code – does little more than strip out docstrings “as-is” and apply some intelligence based on where they are within the code.
* Not well suited for larger projects.
* Limited customization options.
* Might be useful for API documentation, but not for hand written documentation (user guide?).

**Comment by arh89** [comment]
Some of the more common standards for documenting python code can be found here:
http://stackoverflow.com/questions/3898572/what-is-the-standard-python-docstring-format

As was previously noted, if we decide to go down the Sphinx route, both google and numpy styles can be easily parsed (using the Napoleon plugin) - we won't need to radically alter our habits, and producing documentation can have a relatively low developer overhead.

**Comment by arh89** [comment]
An informative discussion on sphinx vs epydoc (and doxygen) can also be found here:
http://stackoverflow.com/questions/5579198/should-we-use-epydoc-sphinx-or-something-else-for-documenting-python-apis

**Comment by arh89** [comment]
Last Wednesday I had an informative discussion with Oliver Sanders in the Rose team. His general view was that Sphinx was "good enough once you can get it to work" (paraphrasing here).

He mentioned that, because Sphinx was a handwritten documentation tool which uses plugins to automatically generate documentation, the setup process can be a little more involved than you might expect - but generally, once everything is setup, it seems to work just fine.

In addition, he advocated the use of the Napoleon plugin, which he found to be very useful in transparently converting from google/numpy formatted docstrings to reST (which Sphinx uses). His personal opinion was that reST was not the most elegant system (something I agree with), but it beats having to write HTML manually! With that in mind, it would be preferable to use Napoleon and write our docstrings in google/numpy format, rather than write reST ourselves...

In addition, his personal opinion was that the google style is preferable to the numpy style, as it tends to take up less vertical space (reducing cases where the documentation is longer than the code!) - I have not checked the format of the docstrings in the existing code (including PRs) - we might have to balance the benefits of using the google style vs time in having to change existing code. I will canvas opinion in the next developer meeting.

He noted that the version of Sphinx provided by default on MO systems was too old to include napoleon, which caused him some issues (I found that using `module load scitools/default-next` provided a newer version which overcomes this difficulty).

Deployment issues with were discussed, and Oliver is happy to provide advice as we move forward, but given that a newer version of Sphinx can be used, and that we can possibly use readthedocs, I don't feel that we should have any significant issues moving forward.

**Comment by arh89** [comment]
Given that the choice seems to be relatively clear in favour of Sphinx, and that no significant risks were highlighted in the discussion with Oliver Sanders,  I do not feel that it is necessary to speak to the Iris team in addition to the Rose team...

( @benfitzpatrick to update acceptance criteria if this is okay).

**Comment by arh89** [comment]
See: https://github.com/arh89/improver/tree/Sphinx_test
For my branch which allows us to test Sphinx on the entire codebase.

Note that I have not really done much to the theme, or edited any of the docstrings to make the code parse better - this is just default sphinx + autodoc + napoleon.

This could form the basis for most of issue #13, provided that the rest of the team is happy with this.
(At that point, things like the tweaking the theme/docstrings and creating some form of documentation generation testing would be done. I figure there's no point in investing much more time in this unless the rest of the team is happy to proceed with Sphinx)...

To build on our machines:
`module load scitools/default-next && cd ~/improver/doc && make apidoc && make html && firefox build/html/index.html`

**Comment by arh89** [comment]
Following a meeting today, it was agreed that the development team is happy to move forward with Sphinx as a documentation tool.

I mentioned possible issues which getting the __init__ methods of a class to be included as part of the autogenerated documentation - this can be addressed by either:

1. Adding constructor docstrings to the bottom of the class docstring.
2. Patching Sphinx in some form
3. Using a newer version of Napoleon (>= 1.5) - and adding `napoleon_include_init_with_doc = True` to the config.py file.

It was agreed that 3. was the best solution, but this would mean requesting a newer version of sphinx to be installed with the next version of the scientific software stack (internally).

However, when using an online service (such as readthedocs), we are able to use newer versions of Sphinx - meaning deployment should not have this issue.

Ticket now moved to closed.
