### ISSUE TITLE
Blackify codebase

### ISSUE THREAD

**Issue by LaurenceBeard** [metoppv/improver#1205]
[Black](https://black.readthedocs.io/en/stable/) removes the need for style checking (pycodestyle) and rule configuration. This should reduce the need for style-correction commits (particularly if used client-side eg. as a pre-commit hook) saving developer time.

**Comment by bayliffe** [comment]
Note that we will all have to get used to its slightly different style choices (and possibly set up our editors accordingly). For example line lengths will not be set hard at 79 characters, instead black endeavours to achieve this whilst making the code readable, so if you variable goes over by a few characters it will probably leave it all on one line.

**Comment by neilCrosswaite** [comment]
# A few key points
The codebase has been blacked by @tjtg and for now can be found [here](https://github.com/metoppv/improver/compare/master...tjtg:black).
# Sad face `):`
The biggest change people might have 'opinions' on is the use of 'sad face' `):`. The sad face is the `):` that is used on its own line.

I quite like this and feel it will look more natural with time.
## for example
```python
if ("title" in cube.attributes.keys() and 
        cube.attributes["title"] != default_title and 
        "Post-Processed" not in cube.attributes["title"]):
    title = cube.attributes["title"]
    cube.attributes["title"] = f"Post-Processed {title}"
```
becomes
```python
if (
    "title" in cube.attributes.keys()
    and cube.attributes["title"] != default_title
    and "Post-Processed" not in cube.attributes["title"]
):
    title = cube.attributes["title"]
    cube.attributes["title"] = f"Post-Processed {title}"
```
# Line length
In Black, I believe the line length is a set number, the default is 88. The choice for 88 rather than 79 or 120 (The two pep chosen lengths) is to do with the average line saving by upping the limit, apparently 79 forces too much code onto new lines whereas 120 makes lines longer with little payoff.

> This number was found to produce significantly shorter files than sticking with 80 (the most popular), or even 79 (used by the standard library).<br>
...<br>
you can pass --line-length with a lower number. Black will try to respect that. However, sometimes it won't be able to without breaking other rules. In those rare cases, auto-formatted code will exceed your allotted limit.<br>
You can also increase it but remember that people with sight disabilities find it harder to work with line lengths exceeding 100 characters. It also adversely affects side-by-side diff review on typical screen resolutions. Long lines also make it harder to present code neatly in documentation or talk slides.
> - [black README](https://github.com/psf/black)

# Arrays
Black loves to put all array items onto one line or one item per line, this can get messy.
## An example of a change is
```python
data = np.array([[[1.0, 0.9, 1.0,
                   0.8, 0.9, 0.5,
                   0.5, 0.2, 0.0]],
                 [[1.0, 0.5, 1.0,
                   0.5, 0.5, 0.3,
                   0.2, 0.0, 0.0]],
                 [[1.0, 0.2, 0.5,
                   0.2, 0.0, 0.1,
                   0.0, 0.0, 0.0]]], dtype=np.float32)
```
becomes 
```python
data = np.array(
    [
        [[1.0, 0.9, 1.0, 0.8, 0.9, 0.5, 0.5, 0.2, 0.0]],
        [[1.0, 0.5, 1.0, 0.5, 0.5, 0.3, 0.2, 0.0, 0.0]],
        [[1.0, 0.2, 0.5, 0.2, 0.0, 0.1, 0.0, 0.0, 0.0]],
    ],
    dtype=np.float32,
)
```
## Second example
```python
expected = np.array(
            [[[25.00, 25.00, 25.00],
              [25.00, 25.00, 25.00],
              [25.00, 25.00, 25.00]],
             [[45.00, 32.50, 32.50],
              [32.50, 32.50, 32.50],
              [32.50, 32.50, 32.50]]])
```
becomes
```python 
expected = np.array(
    [
        [[25.00, 25.00, 25.00], [25.00, 25.00, 25.00], [25.00, 25.00, 25.00]],
        [[45.00, 32.50, 32.50], [32.50, 32.50, 32.50], [32.50, 32.50, 32.50]],
    ]
)
```

# format on/off
Formatting can be turned off with `# fmt: off` and `# fmt: on` This might be useful for some of the testing arrays.

# Double quote `"` vs single `'`
As standard, Black changes all single quotes to double quotes. This can be turned off, but probably shouldn't as we use both types indiscriminately.
Black will handle escaping `\"`

**Comment by neilCrosswaite** [comment]
[Try it out now using the Black Playground.](https://black.now.sh/)
