### ISSUE TITLE
Speed up PercentileBlendingAggregator

### ISSUE THREAD

**Issue by LaurenceBeard** [metoppv/improver#1215]
PercentileBlendingAggregator is very slow due to the large number of python loops and calling of np.interp in the innermost loop. 
Fortunately, this code also uses simple numpy arrays rather than cubes, so we could make use of Numba to speed it up, if a pure python speedup isnt possible.
Acceptance criteria:
See GitHub ticket.

**Comment by TomekTrzeciak** [comment]
I had a quick go at it with numba and got about 10x speed up on two available acceptance tests. The problem with numba is deployment, though (not available where we want to use it).

**Comment by BelligerG** [comment]
I've been having a look/think about this every now and then when I get a bit of time, I've come up with some rough code that uses a bit ore vectorised calculations rather than for loops. I've not implemented it into the code and benchmarked it yet so its possible that it's not faster at all, but I wanted to put it here as a potential direction if NUMBA proves too difficult to obtain.

```
y = percentiles

shpe = input_arr.shape

sort_idx = np.argsort(input_arr)
sort_y = y[sort_idx]
row_idx = np.broadcast_to(np.array(list(range(shpe[0])))[:, np.newaxis], input_arr.shape)

sort_x = input_arr[row_idx, sort_idx]

# probably the bottleneck
loc_idx = np.array([x.searchsorted(input_arr) for x in sort_x])

#ub = input_arr.shape[1]-1
lb_idx = np.clip(loc_idx - 1, 0, shpe[1]-1)
ub_idx = np.clip(loc_idx, 0, shpe[1]-1)

# NaNs show OoBs
grads = (sort_y[row_idx[:, None], lb_idx] - sort_y[row_idx[:, None], ub_idx]) / (sort_x[row_idx[:, None], lb_idx] - sort_x[row_idx[:, None], ub_idx])

interp_vals = ((input_arr - sort_x[row_idx[:, None], lb_idx])*grads)+sort_y[row_idx[:, None], lb_idx]
```
