### ISSUE TITLE
Diagnose convective precipitation

### ISSUE THREAD

**Issue by NigelRoberts** [metoppv/improver#135]
As the product owner I want IMPROVER to be able to distinguish between regions with convective precipitation and those with stratiform precipitation.  

Related issues: #I, #J
Documentation of the 3 steps (3 tasks below) is in 
[gradients_for_conv_rain.pdf](https://github.com/metoppv/improver/files/1112395/gradients_for_conv_rain.pdf)

Sub tasks:
- [x] Apply thresholding to fields of grid-to grid gradients (or direct from precipitation rates) to find the occurrences of exceeding a low threshold (typically any non-zero gradient threshold) and a higher gradient threshold (e.g. 5 mm/hr) for each grid square.
- [x] Find the sum of grid squares exceeding the non-zero gradient threshold and a higher gradient threshold within a square neighbourhood around each grid square. This should link the output from task 1 to the existing 2-step square neighbourhood code #104 .
- [x] Obtain a ratio of neighbourhood sums to diagnose whether precipitation is convective or stratiform or mixed and create an array output.

Future work will be needed to create a classification based on the ratio values to give convective, mixed, stratiform, dry. This will initially have to be an educated first stab based on work by Nigel Roberts and will need refining in future based on case studies.

Acceptance criteria:
 * Check that the output values at each grid square in array from task 1 must be 0,1,2,3 or 4 only (if using double counting of gradients) or 0,2 or 2 (if using single counting of gradients). See [gradients_for_conv_rain.pdf](https://github.com/metoppv/improver/files/1112395/gradients_for_conv_rain.pdf) about double or single counting.
* Make sure that the final ratios can only lie between 0 and 1. 
* Make sure that the divide by zero possibility is accounted for so that neighbourhoods with zero non-zero gradients can be classed ad "dry" 
 * Unit tests
 * Plug-ins for the tasks that need them

**Comment by gavinevans** [comment]
As part of this ticket, I noted the misuse of units according to the CF conventions for `precipitation_amount`. This has been fixed in #182.

My current understanding of this issue is that it involves:
* If requested, calculate the differences between adjacent grid squares.
* Apply a lower and higher threshold to the input cube.
* Apply neighbourhood processing to the lower and higher threshold cubes.
* Calculate higher_threshold_cube/lower_threshold_cube to determine the convective ratio.

The convective ratio gives an indication for where sharp changes in precipitation rate occurs between adjacent grid squares.

This functionality has been implemented so far as a plugin, which in turn calls other plugins.

**Comment by gavinevans** [comment]
Possible follow-on work:
Note that the metadata deficiencies with the threshold plugin are already recorded in #130.
* The `threshold` plugin has an unexpected check to raise an error if the threshold is equal to zero. This check might make sense if the input cube contains probabilities but for other applications it would be reasonable for the threshold to be zero, for example, temperatures in Celsius at zero. In summary, make sure that the `BasicThreshold` plugin works for cubes that don't contain probabilities.

**Comment by gavinevans** [comment]
Just a general note for this issue, it might be worth investigating some time whether there might be alternative solutions for solving this problem, for example making use of the OpenCV library e.g. https://stackoverflow.com/questions/7765810/is-there-a-way-to-detect-if-an-image-is-blurry/7768918#7768918.

**Comment by bayliffe** [comment]
Slide added. Good work, thanks.

**Comment by gavinevans** [comment]
Although this issue is now closed, @fionaRust has a few queries regarding the handling of the convective ratio.

Concerns from @fionaRust:
- Potential for the neighbourhooding of the difference between adjacent grid squares resulting in a non-zero convective ratio being calculated where there was no precipitation within the original precipitation rate cube.
- Differentiation between an area of no precipitation and an area with a constant precipitation rate (i.e. 0 difference) between adjacent grid squares, and whether there was any requirement to handle these differently. Currently, both these situations will return NaN for the convective ratio, as they will both result in 0/0 calculations.
