### ISSUE TITLE
E-W and N-S orography gradient field

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#162]
Part of Epic #97 

As a Improver developer I need fields that enable me to spread probabilities in a orographically appropriate manner (e.g. not spreading the high risk of fog in a valley up the surrounding hill sides). To do this I need fields of orography gradient calculated in the x and y directions only (not diagonal).

Acceptance criteria:
* Create CLI to enable creation of diagnostic gradient fields using adjacent cell gradient plugin (in utilities.spatial).
* Produce an example field using orography as input and check output.

**Comment by gavinevans** [comment]
@bayliffe I think that there might be the need for a follow-on issue in order to make sure that the structure of the directory containing the CLI test data is optimal. I think as we write more tests the top-level `$IMPROVER_ACC_TEST_DIR` directory might get quite full, so may be there would be a better way to structure this directory.
