### ISSUE TITLE
land_fraction diagnostic

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#165]
Part of Epic #97 

As a Improver developer I need a land fraction field that reflects real (as in real world) fractional land area within a given grid square. I need this at first across the UKVX domain.

Acceptance criteria:
* Obtain data that can be used to generate a fractional land area map across the UKVX domain and ensure this data is formatted suitably for easy reuse in the future (to complete the following step for new standard grids) and put it somewhere accessible.
* Create a new land_fraction diagnostic by calculating land area within each grid square in the UKVX standard grid V1.

[09/08/17 @bayliffe  removed redundant information]

**Comment by bayliffe** [comment]
I have extracted data covering the UKVX domain from the MCD12Q1 dataset using the NASA AppEEARS system linked above. A complete description of the data therein can be seen here:

https://lpdaac.usgs.gov/about/news_archive/modisterra_land_cover_types_yearly_l3_global_005deg_cmg_mod12c1

Iris can read the netCDF file output, which will contain three cubes of which we need the IGBP data in cube 1 (of 0-2). The cube dimensions are (Time, Y, X), where Y is measured from the top of the domain; native plotting of the cube will be inverted, so use ::-1 for something more familiar.

The fill value for water is 0, all other surface types are >0, so we can calculate the land fraction with this simple discrimination.

**Comment by bayliffe** [comment]
I sent an email to C.Pelley regarding the use of ANTS to generate this data and await a reply. Further discussions with M. Brooks suggest this is the correct course to get the data we need. There remains a discussion about whether we need to issue the means of producing such ancillaries as part of Improver, or whether a user is responsible for providing their own ancillaries.

**Comment by fionaRust** [comment]
More detail on Jira ticket IMPRO-192

**Comment by fionaRust** [comment]
## DoD checklist

If IMPROVER code change:
 
- [ ]  Meets acceptance criteria in issue (if it is a bugfix PR, the bugfix PR should accurately spell out the problem being fixed with a user story). **_-N/A_**
- [ ]   Meets [code style guide](https://github.com/metoppv/improver/wiki/Code-Style-Guide). **_-N/A_**
- [ ]   All new plugin functionality unit tested if it is reasonable to do so (i.e. if the code is anything other than obvious). **_-N/A_**
 - [ ]  CLI acceptance tests have been added if CLI has been added. **_-N/A_**
- [ ]  All tests pass (should be run locally using /bin/improver-tests as well as checking travis passes). **_-N/A_**
- [ ]   Codacy GitHub check passes (if Codacy raises something unreasonable, ask for a tweak to be made to Codacy settings to allow it to pass) **_-N/A_**
- [ ]  Known bugs fixed, or follow-on issues have been raised. Make sure the product owner is aware of any follow on tickets that have been raised.  **_-N/A_**
- [ ]    Reviewed by at least one person, but always at least 2 for serious non-bugfix changes.
- [ ]  Ensure licence information referred to in the [code style guide] **_-N/A_**(https://github.com/metoppv/improver/wiki/Code-Style-Guide) is included within any new files.
- [ ]   Prepare input to sprint demo e.g. slides. **_-Needed?_**

**Comment by gavinevans** [comment]
A slide has been added.
