### ISSUE TITLE
Implement the optical flow algorithm for radar precipitation - Part I

### ISSUE THREAD

**Issue by MoseleyS** [metoppv/improver#167]
Stephen Moseley as Nowcasting Lead Scientist wants to have the capability to extrapolate radar precipitation rate fields forward in time to use for nowcasting. 

Related issues: Belongs to Epic #132.

This story covers only these component parts:
- [ ] Method to derive advection velocities using Martina's STEPS Python optical flow method (see Stephen's home directory `from_Martina/Decomposition_2017.py`: Class `OFC` (550 lines))
- [ ] Method to derive advection velocities using OpenCV optical flow code. `flow = cv2.calcOpticalFlowFarneback(frame1, frame2, 0.5, 3, 15, 3, 5, 1.2, 0)`
- [ ] Demonstrate difference in advection velocities between these two methods using a simple constructed scenario.

Acceptance criteria:
 * Have plugin(s) in a branch which can use these algorithms.
 * Suitable testing
 * Make a note of relative performance if possible (timings).
 * Demonstration showing how the two advection velocities methods compare in a simple case (<=3 days)

NB, Further scientific testing will be tackled in a future issue #177

**Comment by MoseleyS** [comment]
Working in branch `167_optical_flow_part1`. First version imports Martina's module and successfully executes it and returns a valid CubeList. I have not verified that the data are correct yet.
To use this branch, you need an additional statement in your `etc/site-init` file. Look in mine to find it.

**Comment by MoseleyS** [comment]
I have documented the results of the two optical flow algorithms in the Confluence Nowcasting/Optical Flow Methods page including a Jupyter Notebook if anyone wants to revisit the same data.
I would have liked to include a standardised test too, but I have run out of time.

In conclusion, the STEPS Optical Flow algorithm appears to be more suitable for use with precipitation fields.

**Comment by gavinevans** [comment]
@MoseleyS This looks like an interesting piece of work. It's good to make use of the Jupyter notebook functionality. As some initial comments, I think that more comments are needed in the Jupyter notebook to better indicate what you're doing and so that it's clear what each plot shows. It would be good to include the timings that you've observed for STEPS vs. OpenCV within the Confluence page, just to make this easier to find. On the Confluence page, it would also be useful to add a few sentences as a conclusion to describe what the take home message should be from the comparison of STEPS and OpenCV. 

Following this initial use of Jupyter notebooks, it might be worth thinking about how to push forward the usage of Jupyter notebooks by e.g. using [JupyterHub](https://jupyterhub.readthedocs.io/en/stable/), pushing notebooks to GitHub (https://github.com/blog/1995-github-jupyter-notebooks-3) or using [binder](http://mybinder.org/). It might be worth thinking about whether we want the Jupyter notebooks to provide a full audit trial of the investigation performed, or to just use them as a base from which multiple plots can be produced with these plots saved elsewhere.

**Comment by bayliffe** [comment]
It would be useful if you could add an end-time radar image to the confluence page so that the velocity fields resulting from the two methods can be eyeballed against the actual progress of the precipitation. The wind vectors over northern France are quite different between the methods, I presume due to the lack of precipitation that seems to thwart the OpenCV method. Still, it would be nice to see reality.

**Comment by MoseleyS** [comment]
I have updated the Jupyter Notebook with additional comments (and included an HTML View of it). I have added the timings to the Confluence page and also later radar images.

**Comment by bayliffe** [comment]
The acceptance criteria have been fulfilled and the comments largely addressed, issues around Jupyter notebooks notwithstanding. I think this ticket can now be closed as it provides a suitable foundation for the follow on tickets.
