### ISSUE TITLE
Silhouette calculation

### ISSUE THREAD

**Issue by jrmiro** [metoppv/improver#1674]
Hi! I was working with the wind downscaling module and it asks for the silhouette roughness as a mandatory parameter. I have read in different papers the concept of silhouette but I do not excatly know how to calculate it. In this sense I am a bit confused on how to calculate the "average of up-slopes per unit length over several cross-sections through a grid cell". Can you please provide some guides to address this problem?

Thank you

**Comment by bjwheltor** [comment]
Hi @jrmiro - Sorry for the delay in responding. The wind downscaling was originally implemented in our current operational post-processing system (not IMPROVER) in Fortran and was re-implemented in python in IMPROVER more recently, but we are not currently using it and it's been a while since anyone directly worked on it.

As you are probably already aware the wind downscaling is based on the approach in  [Howard T, Clark P (2003), Correction and downscaling of NWP wind speed forecasts, Meteorological Applications, Volume 14, Issue 2, pages 105–116](http://onlinelibrary.wiley.com/doi/10.1002/met.12/abstract;jsessionid=8BCB440ABB39E747139D6AB25E63DBD1.f04t03), but this only provides the brief explanation of silhouette roughness that you already have. Unfortunately, the details of the method of calculation within the Met Office Unified Model is only fully documented in internal Met Office documentation that cannot be shared in their current form.

In the longer term, we will aim to extend the IMPROVER documentation to cover this, but to provide a more immediate response, I will add some information on the method here (based on internal notes that we have from when this was last developed in the post-processing area), which should give a good indication of what the expectation is.

**Silhouette roughness**

Silhouette roughness (sometimes referred to as A/S or AonS or a_over_s) is calculated as the sum of positive height increments in a high resolution orography along a cross-section of the model grid cell. This considers all high resolution cells intersected, with height decreases being ignored. This is illustrated for two different cases in the figures below, where the red lines show the contributing increments.

![image](https://user-images.githubusercontent.com/9378663/155353998-999a179d-46db-4fb6-a1c6-551d9813fbd5.png)

However, rather than using a single cross-section of the model grid cell, an average is taken over 6 cross-sections shown in the figure below.

![image](https://user-images.githubusercontent.com/9378663/155354438-a25e560c-967d-47a3-9550-9bc4f2c5a1f6.png)

Hopefully, this helps, but I'm happy to try to answer any further questions that you may have.

**Comment by jrmiro** [comment]
Hi @bjwheltor,

Thank you very much for your message and the clarity of your answer. It will help us a lot to calculate the silhouette rougness, for sure. As you said, the concept was clear but it is good to know how the silhouette roughness calculation is carried out in order to do it as much similar as the original method.

Kind regards,
