### ISSUE TITLE
Need gen_landmask function

### ISSUE THREAD

**Issue by NMC-DAVE** [metoppv/improver#1794]
Hi:
       I want to produce my landmask file. So can you 
provide the gen_landmask function code? Thanks very
much.
                                                                  Dave

**Comment by gavinevans** [comment]
Hi Dave,

We don't have any specific code available for generating a land-sea mask. This is because this is potentially something that is supplied by, or created from, the NWP (Numerical Weather Prediction) model that you are trying to post-process and therefore would be specific to the details of the NWP model output e.g. the file format and metadata. 

In terms of what the land-sea mask should look like, this is an example for a UK domain:

![land_sea_mask](https://user-images.githubusercontent.com/26933341/187473379-3dfd58f5-4c31-4251-bda3-5289e4a51817.png)

Land points are set to one whilst sea points are set to zero.

When loaded into [Iris](https://scitools-iris.readthedocs.io/en/latest/#), this land-sea mask should look something like as shown below. The `institution`, `source` and `title` are  [expected attributes](https://github.com/metoppv/improver/blob/master/improver/metadata/constants/attributes.py#L33), which should be amended to whatever is suitable for your data.

![land_sea_mask_cube](https://user-images.githubusercontent.com/26933341/187474220-cc915245-2c9d-4521-83d4-a93adbda0f8f.png).

Hopefully that makes sense.

**Comment by NMC-DAVE** [comment]
Thanks very much!
