### ISSUE TITLE
Upgrade numpy version in production software stack

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#1946]
numpy is currently pinned in our environments to versions around ~1.20. It would be beneficial to update this to more current version (currently 1.26). This ticket covers looking at this issue and understanding whether there are any issues that prevent us from upgrading, addressing them if possible, or recording timescales on which they might be overcome if they are not immediately solvable.

Acceptance criteria:
- improver environments updated to make use of newer numpy versions, ideally 1.26
- OR if this is not possible now, the reasons for this are recorded and future work is spun up to perform this upgrade when possible.

**Comment by cpelley** [comment]
I was just thinking about this in the context of prep. for a post PS46 world :)
I see that our actions conda latest has numpy pinned to 1.27 which isn't much better:
https://github.com/metoppv/improver/blob/dada0c7c6709fb5fa174cae3333c8592d0bb6b5f/envs/latest.yml#L19

Ideally, it would be nice to target a 'latest' that represents the unpinning of all packages.
improver code and testing should ideally then be made to specify minimum package versions where appropriate rather than maximum ones.  Clearly this would be made less work when we no longer need to target the old oper. environments.

**Comment by bayliffe** [comment]
@bayliffe talk to Carwyn about the future of this ticket and its ownership.

**Comment by bayliffe** [comment]
@cpelley shall we close this ticket and leave the environment management largely with the technical team? That would be preferable, though I assume there will be some questions for the science team if issues arise. We will also be available to help with plugin changes that are required, e.g. due to changes to the iris import approach.

**Comment by cpelley** [comment]
Tidy.  I'll open an issue on the green team board highlighting the need to explore extending the testing frameworks of a given repository to compare results for different versions of libraries (in particular visual comparisons using matplotlib).
