### ISSUE TITLE
Triangular weighting function

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#202]
Prerequisite for completing issues #188 #189 

As an IMPROVER developer, I need a function or plugin that can apply a triangular weighting function to data along a spatial or time axis. The width of the triangle should not be assumed to have limits at discrete points (e.g. grid points, model levels), but rather will be on a continuous scale, and this width should be an input parameter.

**Examples**
**Spatial:** if two bands are 0-100m and 100-200m, a location at 100m would include probabilities from each band with a weighting of 50% each. A location at 150m would have probabilities much more weighted in the 100-200m band.

**Temporal:** the model may give a non-zero probability of rain occurring sometime within the time period 12.00 to 18.00 and it really rains at 18.10. By application of a triangular weighting function this probability can be spread to account for temporal uncertainty.

There will need to be tests to avoid spanning into invalid regions (e.g. underground, negative time).

**NB:** Ideally there should be the flexibility to span more than one band (e.g. precip accumulation band, or vertical level band) on each side of the triangle, but not if this becomes much more complicated and slow because it is then easier to set the bands appropriately first and then constrain the triangular weighting function to span no more than one in each direction. 

Related issues: #188 #189 

Document about time windows for precipitation accumulations: 
[time_windowing_accumulations.pdf](https://github.com/metoppv/improver/files/1161842/time_windowing_accumulations.pdf)

Acceptance criteria:
 * Triangular weighting function/plugin.
 * Provides for a definable triangular weighting width.
 * Works for any axis.
 * Unit tests.

**Comment by fionaRust** [comment]
I've read the attached pdf and I have a few comments:
1. It makes the wrong assumption about the format of the precipitation accumulation inputs. They will come as accumulations with the specific period (not from the start of the forecast) as StaGE will do the processing for us. I don't think this will make any difference to how we do things though.
2. I'm not sure the processing chain for the second form we are trying to calculate () is quite right. But again I don't thing that will have much impact in this ticket.
3. The triangular functions are not linear, but again I don't think this will cause many problems.

**Comment by fionaRust** [comment]
I have a provisional PR available here:

I have a few comments:
* I have created a function to do linear triangles, with the same slope either side of the peak. I'm not sure this is what Nigel invisaged based on his pdf document, as he has described a different way of calculating weights. I could implement his non-linear triangular weights in stead of or as well as the linear triangle I've implemented.
*  I have not implemented the functionality with

**Comment by gavinevans** [comment]
## DoD checklist

If IMPROVER code change:
 
- [x]  Meets acceptance criteria in issue (if it is a bugfix PR, the bugfix PR should accurately spell out the problem being fixed with a user story).
- [x]   Meets [code style guide](https://github.com/metoppv/improver/wiki/Code-Style-Guide).
- [x]   All new plugin functionality unit tested if it is reasonable to do so (i.e. if the code is anything other than obvious). 
 -  CLI acceptance tests have been added if CLI has been added. N/A
- [x]  All tests pass (should be run locally using /bin/improver-tests as well as checking travis passes). 
- [x]   Codacy GitHub check passes (if Codacy raises something unreasonable, ask for a tweak to be made to Codacy settings to allow it to pass) 
- [x]  Known bugs fixed, or follow-on issues have been raised. Make sure the product owner is aware of any follow on tickets that have been raised. 
- [x]    Reviewed by at least one person, but always at least 2 for serious non-bugfix changes.
- [x]  Ensure licence information referred to in the [code style guide] (https://github.com/metoppv/improver/wiki/Code-Style-Guide) is included within any new files.
- [x]   Prepare input to sprint demo e.g. slides.
