### ISSUE TITLE
Add topographic bands coordinate

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#231]
As an IMPROVER developer, I want the cubes to have a topographic bands coordinate so that I can process topographic bands in the same way as other coordinates e.g. time, realization.

Related issues: #202 

Pre-requisite: #188, #189 

Acceptance criteria:
 * Replace the metadata convention for a `topographic_band_lower` and `topographic_band_upper` with a single coordinate with a point and bounds.
 * Ensure that this is compatible with the usage of topographic bands for ancillary generation and for the triangular weighting function (#202).
 * Agree suitable naming convention for the "topographic_bands" coordinate and add to Metadata Confluence page.
 * Unit tests

**Comment by fionaRust** [comment]
We will probably need to be able to have a cube with multiple fields that have been processed in the same way but across different topographical bands. We can then blend across bands where appropriate using the triangular weighting function for a point which is close to the boundary between bands. This blending may take place after the neighbourhooding step across each band (but any changes to the metadata in the output cubes from neighbourhooding will probably be covered by #188 anyway).

**Comment by wxtim** [comment]
PR #238 created.
This addresses the first bullet point only at the moment.

**Comment by PaulAbernethy** [comment]
It would probably be a good idea to test that this works with the triangular weighting. Try merging two cubes across different bands.

Naming convention seems fine for now.

**Comment by PaulAbernethy** [comment]
## DoD checklist

If IMPROVER code change:
 
- [ ]  Meets acceptance criteria in issue (if it is a bugfix PR, the bugfix PR should accurately spell out the problem being fixed with a user story). **_-Almost there_**
- [x]   Meets [code style guide](https://github.com/metoppv/improver/wiki/Code-Style-Guide). **_Yes_**
- [x]   All new plugin functionality unit tested if it is reasonable to do so (i.e. if the code is anything other than obvious). **__**
 - [ ]  CLI acceptance tests have been added if CLI has been added. **_-Added, but not all tests pass_**
- [ ]  All tests pass (should be run locally using /bin/improver-tests as well as checking travis passes). **_False_**
- [x]   Codacy GitHub check passes (if Codacy raises something unreasonable, ask for a tweak to be made to Codacy settings to allow it to pass) **__**
- [x]  Known bugs fixed, or follow-on issues have been raised. Make sure the product owner is aware of any follow on tickets that have been raised.  **__**
- [ ]    Reviewed by at least one person, but always at least 2 for serious non-bugfix changes.
- [ ]  Ensure licence information referred to in the [code style guide] **_-N/A_**(https://github.com/metoppv/improver/wiki/Code-Style-Guide) is included within any new files.
- [ ]   Prepare input to sprint demo e.g. slides. Needs a slide or two

**Comment by wxtim** [comment]
Comparison of the old kgo and the output of the cli
```python
>>> len(kgo) == len(new)
True

>>> for cube in kgo:
...  try:
...   print cube.coord('topographic_bound_lower').points ,cube.coord('topographic_bound_upper').points
...  except:
...   print cube.coord('topographic_bound_lower').points , " no upper bound"
... 
[400] [500]
[500] [600]
[-500] [0]
[0] [50]
[50] [100]
[100] [150]
[150] [200]
[200] [250]
[250] [300]
[300] [400]
[600] [600]  no upper bound


>>> for cube in new:
...   print cube.coord('topographic_zone').bounds
... 
[[500 600]]
[[-500  600]]
[[ 0 50]]
[[ 50 100]]
[[100 150]]
[[150 200]]
[[200 250]]
[[250 300]]
[[300 400]]
[[400 500]]
[[-500    0]]




```

**Comment by wxtim** [comment]
## New KGO.nc file
can be found at 
/home/h02/tpilling/temp_improver/IMPRO-231_single_topographic_band_coord
