### ISSUE TITLE
Determine snow probability from falling snow level and precipitation in neighbourhood

### ISSUE THREAD

**Issue by NigelRoberts** [metoppv/improver#257]
As the product owner I want IMPROVER to be able to discriminate between rain and snow using the falling snow level to detect the melting zone and a neighbourhood to find the fraction of precipitation in order to generate a probability of snow or rain.

The falling snow level is needed to allow a neighbourhood approach for determining whether the precipitation is snow or rain. This could be computed in terms of either percentiles or probabilities. This issue describes the percentiles approach with a probabilities approach described in a comment below.

Percentiles approach:

Steps:
[Steps 1-3 are the final steps of the snow level linear processing chain preceding its combination with the linear precipitation chain in the suite - see snow chain diagram]
1. For a given forecast or ensemble use the falling snow level from #195 and neighbourhood processing to generate falling snow level percentiles at every grid square using a square neighbourhood. Percentiles can be every 10% (or even 20% to start with). For an ensemble this will involve then combining members as well as neighbourhood values to determine the percentiles. A short-cut of finding the mean of each percentile is viable to start with to show the proof of concept. Therefore in simple terms, this involves finding the ensemble mean, and then using the existing functionality to generate percentiles from a neighbourhood.
2. Convert the falling snow level percentile value into a probability of the precipitation type being snow at each grid square by applying thresholding.
[Step 4 describes a final step in the precipitation chain (square neighbourhooding) and then the suite combination step - architecture for which will be implemented in IMPRO-339]
 3. Multiply the falling snow level probability by the probability of precipitation rate above a threshold (e.g. >0.02mm/hr) in a square neighbourhood around each grid square (same size as neighbourhood in step 2) to give a probability of falling snow at each grid square.

This ticket involves the testing of the existing code chained together prior to integrating within the suite, in order to resolve problems with the interfaces early. A separate issue will integrate the snow probability chain into the suite. 

Acceptance criteria:
 * Fix any small problems found.
 * Make sure that excessively grid-specific information has been avoided.
 * Visual examination of output, preferably within a shareable jupyter notebook.

**Comment by gavinevans** [comment]
Alternative approach using probabilities instead of percentiles:

An alternative approach is to construct probabilities for a set of altitudes and then obtain the probability at each grid square.
1. For altitudes at intervals of every 50 or 100m find the probability that any precipitation will be snow.
- fuzzy (bounded) thresholding (+/- 50% of altitude band width) for each altitude level.
- square neighbourhood processing (the same size as for the precipitation probabilities) for each altitude level
2. Use linear interpolation of the probabilities at each altitude level to determine the probability at each grid square.
3. Multiply the falling snow level probability by the fraction of precipitation rate above a threshold (e.g. >0.02mm/hr) in a square neighbourhood around each grid square (same size as neighbourhood in step 2) to give a probability of falling snow at each grid square.

Each method has pros and cons. The percentiles approach captures the ends of the height level distribution by default and doesn't have the redundancy of the probabilities method when the snow level is a long way above the ground. On the other hand, the probabilities method is probably quicker.

**Comment by gavinevans** [comment]
Completed in #402 and #410.
