### ISSUE TITLE
improver wind-downscaling: ensure output is float32 not double

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#435]
As an IMPROVER developer I want my wind downscaling to process data at a precision of 32 bits so that my calculations are faster. I want to avoid unnecessary escalation to 64 bits, and ensure that the final output is also of 32 bit precision.

Acceptance criteria:
 * Change any steps within wind downscaling that escalate the float precision to 64 bit.
 * Ensure final output precision is 32 bit.
 * Update KGO acceptance test data
 * Add a unit test to explicitly check for this

**Comment by MarkWorsfold** [comment]
Created pull request:
https://github.com/metoppv/improver/pull/466

Change any steps within wind downscaling that escalate the float precision to 64 bit. - Complete
Ensure final output precision is 32 bit. - Complete
Update KGO acceptance test data - Not done because need to change data in test dir
Add a unit test to explicitly check for this - Complete.

**Comment by bayliffe** [comment]
Completed.
