### ISSUE TITLE
Document Blended Weights function (generation of weights)

### ISSUE THREAD

**Issue by seanpcoultas** [metoppv/improver#45]
[timelag_blending_function_NR310517.pdf](https://github.com/metoppv/improver/files/1041960/timelag_blending_function_NR310517.pdf)
Assign to Nigel Roberts

As a X I want Y so that Z

Related issues: #I, #J

Optional extra information text goes here

Acceptance criteria:
 * A
 * B
 * C

**Comment by gavinevans** [comment]
The acceptance criteria for this are a little vague(!), but the report looks useful. My only confusion would be that you sometimes "6-hour forecast" and "12-hour forecast" are used to describe forecasts at T+6 and T+12. I think that "6 hour forecast" is a bit ambiguous, as you could be referring to a forecast with a total run length of 6 hours, rather than the T+6 forecast, which I think you mean.  Otherwise, this report looks informative!

**Comment by NigelRoberts** [comment]
Thanks Gavin. 

I'll change the "6 hour forecast" bits

**Comment by fionaRust** [comment]
Moved back to in progress as agreed in the Stand-up. Seems like it needs more work.

**Comment by carolinejjones** [comment]
Nigel,

A few comments on the document.

1. Is there a reason why we are just addressing time-lagging in this document?

2. I would lose 6-hour/12-hour from the following statement and just have "a forecast may be combined with an older forecast" as the 6-hour/12-hour doesn't add anything and just makes it less understandable

> For example, a 6-hour forecast may be combined with an older 12-hour forecast to produce a forecast that is a compromise between the two

3. The simplest and most scientifically sensible way to do this is to generate a **pdf** for the relevant diagnostic and blend the **pdf** together. I can see what you are trying to say in this paragraph but it is vitally important that the same blending weights are applied to all probability thresholds for the relevant diagnostic. A probability field can be blended by calculating a weighted mean but the same threshold needs to be used for all thresholds or you could in theory end up with inconsistent values. Your comments about a raw field is assuming you are creating a deterministic output rather than treating the data as an ensemble.  

4. I'm assuming that should be a weighted mean rather than addition or am I reading this sentence incorrectly. 
>The simple addition of probabilities is a good pragmatic start

5. I would add a comment after this sentence to the affect that we are limiting ourselves to the last 6 runs for this demonstration. There are more forecasts available for A and B if we were willing to use more runs.
>The grey bars represent 12-hour forecasts starting 1-hour apart with the bar along the bottom representing the most recent forecast that starts at 06UTC

6. We have already discussed the fact that there is no difference between hourly UKV and 3-hourly UKV so this statement needs to be tweaked a bit. The blending of two models and then blending with a third I think will make it much harder to determine the optimal weights; it would make more sense to look at what models are available for at a particular time for a validity time and then determine the weights to give to each model but I guess this is something we need to discuss further.
>firstly the hourly UKV with the 3-hourly UKV (step 5) and then the combined UKV with MOGREPS-UK (step 6).

**Comment by NigelRoberts** [comment]
Hi Caroline

I've just time to address your first point. It is only about time-lagging because it isn't meant to be a general science document about blending. It is just meant to describe a suitable method for computing the weights for time lagging. 

Just on point 3 - yes I agree, the blending weights should be the same for all thresholds for a given lead-time combination of forecasts.

I'll have to have a look at the rest next week.

**Comment by carolinejjones** [comment]
Updating of this document moving to #176
