### ISSUE TITLE
CLI for wind downscaling

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#67]
As a suite developer I want a command line interface to the wind downscaling functionality so that I can write a nice suite that runs this algorithm

Pre-requisite issues: #43 and others
* Ancillary files available.

Acceptance criteria:
 * Write a new `bin/improver-wind-downscale` utility
 * This should take in options/arguments for input and ancillaries
 * Add CLI acceptance tests - technical and known good input/output acceptance tests.. Use input from the archive for known good input.

**Comment by meabhnicguidhir** [comment]
As of now, we have a CLI script that runs and produces output. However, this issue is blocked for now, as we still don't have all the inputs we need. The following inputs are required:
* high res / pp orography (currently using standard orography field for this)
* silhouette roughness (field provided in provisional orography directory has no valid data)
* vegetative roughness length
* height of input speed field

We have adequate inputs for:
* 'standard orography': model orography regridded onto the standard grid
* sigma: model orography standard deviation
* wind speed (taken from pwms output)
* Model resolution (different for each model)

**Comment by meabhnicguidhir** [comment]
Technical Debt Notes:
* Current implementation has an optional input of input speed heights in a cube. If we are using data on the standard grids, then the data will always be on the standard heights. The code should use the height coordinate of the wind speed cube instead of a separate cube of heights.
* Martina has written a document on the wind downscaling which should be referenced more thoroughly from the code.

**Comment by meabhnicguidhir** [comment]
A slide has been prepared for the June demo.

**Comment by gavinevans** [comment]
Follow-on issues #121 and #122 have been opened.

**Comment by fionaRust** [comment]
**Overview**
*  Pr #116 has been merged. New acceptance tests added to central location.
* Technical follow on issues to fix problems with wind downscaling have been raised #121 #122 
* The ancillaries used here have been created by Ben. Once we have a method for creating the ancillaries we need properly we should probably update the tests to use these. @NigelRoberts This should probably be added to the ancillary epic #97
