### ISSUE TITLE
Import percentile conversion

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#69]
As an IMPROVER developer I want ensemble member data to percentile conversion so that I can develop a percentiled products.

Acceptance criteria:
 * Import percentile plugin code from wind demo suite
 * Add unit tests (some in bgd?)
 * Add CLI and CLI test technical and known good input/ output tests.
 * Include 0 and 100 percentiles

**Comment by NigelRoberts** [comment]
Hi Ben,
This functionality is in the roadmap for July. Do you want it earlier?
Nigel

**Comment by fionaRust** [comment]
How different is this to the functionality @gavinevans  has implemented to create percentiles from ensemble mean and variance?

**Comment by gavinevans** [comment]
I think that this would probably be a difference between this functionality and the create percentiles from ensemble mean and variance functionality, but this should be reviewed.

**Comment by bayliffe** [comment]
I have taken the outline code by @benfitzpatrick and added the following:
- Acceptance of multiple coordinates over which to collapse (in the form of a list); this action is commutative if performed in a single step by iris, but otherwise potentially not, so should be done in just one call.
- Type checking of collapse_coord for list input.
- Alphabetical sorting of collapse_coord name order when a list is provided so the resulting percentile coordinate is consistently named. Despite the collapse process being commutative the output percentile coordinate combines the names of the collapsing coordinates in the order in which they are provided. So without this two equivalent collapse procedures could produce percentile coordinates with differing names.
- Added an exception if the coordinates passed to the collapse operation are not actually present in the cube.

**Comment by bayliffe** [comment]
See PR: https://github.com/metoppv/improver/pull/109

**Comment by MoseleyS** [comment]
Too late for the pull request, so I'll put the comment here.
In bin/improver-percentile, the help string should list the default percentiles list.
I can't do any Codacy checks as this ticket has already been merged - I assume these are ok.
The ticket has not yet been added to the Sprint demo presentation.
Otherwise, everything has been done.

**Comment by bayliffe** [comment]
Please see PR#115 to address this additional comment.

**Comment by MoseleyS** [comment]
Additional PR merged, so I consider this ticket done.

**Comment by MoseleyS** [comment]
Sprint demo slide is also present.
